
joy_teleop:
  ros__parameters:
    move:
      type: topic
      interface_type: geometry_msgs/msg/Twist
      topic_name: micro_ros_arduino_twist_subscriber
      deadman_buttons: [7]
      axis_mappings:
        linear-x:
          axis: 7
          scale: 1.2
          offset: 0.0
        angular-z:
          axis: 6
          scale: -18.0
          offset: 0.0